### ISSUE TITLE
Conflicting deprecation information in API docs

### ISSUE THREAD

**Issue by daviddecorso** [amzn/selling-partner-api-models#4080]
[The v2024 use case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#considerations) states that the following APIs **_are not_** being deprecated:
```
getShipments
getShipmentItemsByShipmentId
getShipmentItems
```
However, the [SP-API deprecations page](https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations) suggests that they **_are_** being deprecated.

Which of these is correct? If those APIs are being deprecated, what is meant to replace the `getShipments` endpoint?

**Comment by rugved1991** [comment]
Hi @daviddecorso,

Thanks for flagging this issue. We are reviewing this internally and will make changes to the documentation upon receiving confirmation.

Best,
Rugved
Solutions Architect, SP-API

**Comment by rugved1991** [comment]
Hi @daviddecorso,

The documentation has been fixed. The v0 operations that wont be deprecated have been removed from the SP-API deprecations page. 

Best,
Rugved
Solutions Architect, SP-API

**Comment by adarmanto** [comment]
Hi @daviddecorso,

It still shows deprecation notice via this page (https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference):

<img width="829" alt="image" src="https://github.com/user-attachments/assets/ce1d9eaa-63bb-4248-af61-8acf0dbdbcca">

And also got email notification with similar notice on 14th Aug 2024:

<img width="930" alt="image" src="https://github.com/user-attachments/assets/e6844a65-814f-480b-9694-5b40956cda4a">
