### ISSUE TITLE
Incorrect and duplicated records in Xpath to JSON pointer mapping file

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-models#4456]
I'm building [a tool](https://tools.highsidelabs.co/) to automatically convert the old `POST_PRODUCT_DATA` and `POST_FLAT_FILE_LISTINGS_DATA` feed types to the new `JSON_LISTINGS_FEED`. Both the XML and TSV mapping files available [here](https://tools.highsidelabs.co/) have missing/incorrect data. I reported the issues with the TSV mapping file in #4264 (and @johnkw reported it in #4318), but have since discovered issues with the XML mapping file too.

There are tags that are mapped to JSON pointers that simply don't exist in the JSON schemas returned by the Product Type Definitions API. For instance, the XML mapping file contains this record:

```csv
Message/Product/ProductData/Home/ProductType/FlatSheet/ColorMap,,/attributes/color/0/standardized_values/0
```

However, the `FLAT_SHEET` JSON schema returned by the Product Type Definitions API defines the `color` attribute like so:

```json
{
    "title": "Color",
    "description": "Provide the color of the product",
    "examples": [
        "Cranberry"
    ],
    "type": "array",
    "minItems": 1,
    "minUniqueItems": 1,
    "maxUniqueItems": 1,
    "selectors": [
        "marketplace_id",
        "language_tag"
    ],
    "items": {
        "type": "object",
        "required": [
            "language_tag"
        ],
        "properties": {
            "value": {
                "title": "Color",
                "description": "Provide the color of the product",
                "editable": true,
                "hidden": false,
                "examples": [
                    "Cranberry"
                ],
                "type": "string",
                "minLength": 0,
                "maxLength": 1000,
                "anyOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "string",
                        "enum": [
                            "Beige",
                            "Black",
                            "Blue",
                            "Brown",
                            "Cream",
                            "Gold",
                            "Gray",
                            "Green",
                            "Multicolor",
                            "Orange",
                            "Peach",
                            "Pink",
                            "Purple",
                            "Red",
                            "Teal",
                            "White",
                            "Yellow"
                        ],
                        "enumNames": [
                            "Beige",
                            "Black",
                            "Blue",
                            "Brown",
                            "Cream",
                            "Gold",
                            "Gray",
                            "Green",
                            "Multicolor",
                            "Orange",
                            "Peach",
                            "Pink",
                            "Purple",
                            "Red",
                            "Teal",
                            "White",
                            "Yellow"
                        ]
                    }
                ]
            },
            "language_tag": {
                "$ref": "#\/$defs\/language_tag"
            },
            "marketplace_id": {
                "$ref": "#\/$defs\/marketplace_id"
            }
        },
        "additionalProperties": false
    }
}
```

The JSON path that the XML mapping file points to for the Xpath `Message/Product/ProductData/Home/ProductType/FlatSheet/ColorMap`, which is `/attributes/color/0/standardized_values/0`, doesn't exist in that definition. So when I try to map the `ColorMap` tag to that JSON pointer, the resulting `JSON_LISTINGS_FEED` fails to validate against the `FLAT_SHEET` JSON schema.

The other issue I've found is that many attribute mappings are duplicated, with the only difference between the duplicates being that in one of them, the JSON path has an extra space before it. Check the same Xpath as above, for example:

```csv
Message/Product/ProductData/Home/ProductType/FlatSheet/ColorMap,,/attributes/color/0/standardized_values/0
Message/Product/ProductData/Home/ProductType/FlatSheet/ColorMap,, /attributes/color/0/standardized_values/0
```

This problem is more annoying than anything else, as it doesn't actually prevent the file from being used but means that any tool that uses it needs to deduplicate it first.

I would really, really appreciate it if this could get resolved ASAP – I'm sure it's causing issues for many other developers who are trying to make the switch to the `JSON_LISTINGS_FEED` before the deadline.

CC @chapmanjw @puppsupr

**Comment by johnkw** [comment]
Yes, until these bugs are fixed, the `JSON_LISTINGS_FEED` is completely unusable. If `POST_FLAT_FILE_LISTINGS_DATA` really gets deleted before these bugs are fixed, the only possible fallback plan would be to generate the current feed files automatically as everyone is currently doing, and then manually upload the feed via Seller Central.

The deprecation really needs to be postponed until there's some possible way to programmatically perform the upgrade (and to continue to be able to use the template files, which are only available on SellerCentral in the CSV format.)

**Comment by johnkw** [comment]
Is `POST_FLAT_FILE_LISTINGS_DATA` still deprecated without any documented way to migrate?

**Comment by jlevers** [comment]
@puppsupr @MeenaAmz @chapmanjw et al, it would be really, really helpful to get an update on this.

**Comment by ritikacd** [comment]
> [@puppsupr](https://github.com/puppsupr) [@MeenaAmz](https://github.com/MeenaAmz) [@chapmanjw](https://github.com/chapmanjw) et al, it would be really, really helpful to get an update on this.

Hi @jlevers 

This is to update you that we are actively working on updating the mapping files. We will update the thread once new versions are available in the developer documentation. 

Thanks,
Ritika

**Comment by johnkw** [comment]
Would be helpful to remove or extend the time on https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations for `POST_FLAT_FILE_LISTINGS_DATA`, since there still does not exist a documented replacement for the current API.

**Comment by jlevers** [comment]
Please do not close this – this is an ongoing problem, as is #4264.

**Comment by johnkw** [comment]
This critical issue should remain open since `POST_FLAT_FILE_LISTINGS_DATA` is still listed on https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations as deprecated with no documented method of migrating to any alternative.

**Comment by ritikacd** [comment]
Hi @johnkw 

Please refer to the [Migrating flat file feeds workflows](https://developer-docs.amazon.com/sp-api/docs/listing-workflow-migration-tutorial#migrating-flat-file-feeds-workflows) tutorial to understand the requirements for migrating legacy `POST_FLAT_FILE_LISTINGS_DATA` to [Listings Items API](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference) or `JSON_LISTINGS_FEED`. 

Please note with the [Listings Items API](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference) and JSON_LISTINGS_FEED, the workflows have been generalized to “requirements” to identify the type of listing being created or updated. Based on the `requirements`, you can use [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference) to retrieve the attributes and data requirements for creating or updating a listing for a product type. 

Here are other two resources that will help you migrate your application: 
[Listings XSD to JSON Migration Webinar](https://www.youtube.com/watch?v=MJHQPXWwGWo)
[Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide)

Let us know if you have questions about the above resources shared. 

Thanks,
Ritika
Selling Partner API Developer Services

**Comment by johnkw** [comment]
Has the "Product Flat File Mappings" been updated to fix all of the problems with it?

**Comment by ritikacd** [comment]
> Has the "Product Flat File Mappings" been updated to fix all of the problems with it?

Hi @johnkw 
We are expecting to publish the updated file in the next few days. I'll update the thread once it's in production. 

Thanks,
Ritika
Selling Partner API Developer Services

**Comment by RenaudLavoisier** [comment]
Hi

I'm interested by this as well as the current XPATH-To-Json mapping is incomplete, mostly wrong and therefore totally unusable:
- Incorrect XSD paths for a lot of attributes (`Product/DescriptionData/ItemDimensions/Dimensions/Length/LengthDimension/Value` is rendered as `Message/Product/DescriptionData/ItemDimensions/Length` in the file)
- Some json path are not precise enough ex `Message/Product/ProductData/Outdoors/ProductType/CampingEquipment/Size: /attributes/size/0/value` let's you think there is a "size" attribute for the CAMPING_EQUIPEMENT category but there's not (there are `CAMPING_EQUIPEMENT->wheel->size, CAMPING_EQUIPEMENT->head->size...`)

Looking forward for the fixed file

**Comment by RenaudLavoisier** [comment]
To be honest I do agree with @johnkw. It's mindblowing that Amazon is pressuring us with a short deadline to migrate and yet provides such a catastrophic level of documentations / ressources.

**Comment by johnkw** [comment]
So long as the current working API has a pending deprecation date, this is still a crisis in progress and this issue should not be closed.

**Comment by johnkw** [comment]
So long as the current working API has a pending deprecation date, this is still a crisis in progress and this issue should not be closed.

**Comment by johnkw** [comment]
Any update on when the documentation will be fixed to possibly migrate? The deprecation date is now tomorrow, and there's still no way to migrate to the new feed. @ritikacd @puppsupr

**Comment by johnkw** [comment]
I added some fixes in https://github.com/amzn/selling-partner-api-models/issues/4318#issuecomment-3144560513 that need to be incorporated into the official doc.

**Comment by johnkw** [comment]
Now that a `FlatFile-To-JSON-Mapping.csv` was finally published covering the majority of columns, I finally have an appreciation for the specific mess going on over here in this bug.

There are 1388 path collisions in the current `FlatFile-To-JSON-Mapping` document. I just collected them all here: [collisions.txt](https://github.com/user-attachments/files/21552824/collisions.txt)

So currently if you're using that documentation to migrate, something is getting deleted/lost.

**Comment by johnkw** [comment]
Related to the issue of collisions are many properties which aren't well-specified by a "path".  See the following, originally from https://github.com/amzn/selling-partner-api-models/issues/4318#issuecomment-3145298671 

Oh I think maybe it's hidden inside a bizarrely complicated list of dictionaries in `/attributes/nutritional_info/0/vitamins_and_minerals`. Each one seems to get a separate row with a name that's generated mysteriously from some other mapping. I just realized all of those are being incorrectly collided onto the same path.

Looking at an example `getListingsItem` call, it appears the format of this section is a list of dictionaries where the identifier is hidden in a field called "nutrient" instead of just being the dictionary key for that section as one might expect. What a bizarrely complicated mess.
```
    "vitamins_and_minerals": [
     {
      "nutrient": "calcium",
      "string_value": "110",
      "unit": "milligrams",
      "value": "110.00"
     },
     {
      "nutrient": "iron",
      "string_value": "2.7",
      "unit": "milligrams",
      "value": "2.7"
     },
     {
      "nutrient": "potassium",
      "string_value": "880",
      "unit": "milligrams",
      "value": "880.00"
     },
     {
      "nutrient": "sodium",
      "string_value": "0.95",
      "unit": "grams",
      "value": "0.95"
     }
    ],
```
It's not obvious how this could even be described in the form of a JSON path. (Assuming they wanted to do all of these pointlessly complicated nested structures, what a huge mistake they made not to just to make it be a dictionary like `"vitamins_and_minerals": { "calcium": { ... } }` which could at least then be expressed in the form of the path.)

But can we somehow assume that whenever anything in the `/attributes/nutritional_info/0/vitamins_and_minerals` is used, that you can just magically chop off the `_per_serving` part of `calcium_per_serving` and use that as the `nutrient` key?

It's worth nothing that it was only a couple days ago the a migration path was even documented at all, and the deprecation date has already passed. The deprecation date for the current feeds should be pushed out at least a few months to give time to look at all this now that there's some documentation on migration.

**Comment by johnkw** [comment]
It seems like `POST_FLAT_FILE_LISTINGS_DATA` may have actually been disabled today? It's constantly failing now. Unfortunate since there still is no documented migration method available for all of the fields, like those listed above.

**Comment by ritikacd** [comment]
Hi @johnkw 

As [planned](https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations#feeds-api), support of the legacy XML and flat file product feeds is now deprecated. 

For the missing mappings, call [getProductTypeDefinitions API](https://developer-docs.amazon.com/sp-api/reference/getdefinitionsproducttype) by product type to see the JSON path of the attributes. You can retrieve the product type for the existing listings by passing `productTypes` in the [getListingsItem](https://developer-docs.amazon.com/sp-api/reference/getlistingsitem) API. 

Thanks,
Ritika C. 
Selling Partner API Developer Services

**Comment by johnkw** [comment]
`getdefinitionsproducttype` does not return useful information. For example, many fields which exist in the CSV are missing entirely. It also contains very large amounts of fields which are not part of the actual attributes that exist for that category.

Any answer on how to map the missing fields? Is there some specific way to find the ones (such as "calcium") which are missing entirely from `getdefinitionsproducttype`?

Also any word on the massive amount of "collisions" in the `FlatFile-To-JSON-Mapping` migration document?

**Comment by johnkw** [comment]
Since there's still no documented programmatic method to map fields over to the complicated JSON hierarchy, we're using https://sellercentral.amazon.com/product-search/bulk uploads for now.  It's worth noting that the API continues to work for those submissions and you get a status update as usual on the feed ID (which is shown on sellercentral).  So sellercentral apparently has some back-door way to continue doing the feeds similar to before.  It would be very helpful to ensure at least that the feed status GET call continues to work, pending completed documentation on migrating to the new method.

**Comment by RenaudLavoisier** [comment]
> Since there's still no documented programmatic method to map fields over to the complicated JSON hierarchy, we're using https://sellercentral.amazon.com/product-search/bulk uploads for now. It's worth noting that the API continues to work for those submissions and you get a status update as usual on the feed ID (which is shown on sellercentral). So sellercentral apparently has some back-door way to continue doing the feeds similar to before. It would be very helpful to ensure at least that the feed status GET call continues to work, pending completed documentation on migrating to the new method.

Sadly I think you will be out of luck trying to get any help from them on that matter. We talk to a lot of people at Amazon in our company and they have mostly no ideas how it works or what's going on.

We managed to decipher the file with lots of efforts and with the help of IA to try to exctract but their is still fields we didn't manage to match so it was a  manual task. 
We also have issues using the actual API fo which we are still to get clear explanations.

**Comment by ritikacd** [comment]
Hi @RenaudLavoisier @johnkw 
 
As the scope of the original issue has been resolved, would you be comfortable if we close it?

Thanks,
Ritika

**Comment by johnkw** [comment]
This is definitely not resolved, and should remain open until there's an answer. There's no way to programmatically go from the simple CSV names to the new complicated JSON hierarchies. And there's still no way to even ask Seller Support about the documentation for one of the new complicated JSON hierarchies -- they will only comment on the simple feed names.

**Comment by RenaudLavoisier** [comment]
This is not resolved at all. We just had to found a convoluted way to make it work.

The fact that this is still in this state and that you will ask money next year to use the SP-API is mind blowing

**Comment by johnkw** [comment]
It only says we'll be charged for "production usage of SP-API" and the current SP-API is not ready for production usage, so presumably we'll all be exempt from fees until these bugs are fixed?
