### ISSUE TITLE
Inconsistent OrignalTotal 

### ISSUE THREAD

**Issue by shlomieconnect** [amzn/selling-partner-api-models#4535]
![originalTotalDiscrepancy](https://github.com/user-attachments/assets/330a03c4-fc82-45ee-9b34-42610ddbc885)

There seems to be a discrepency in the original total returned when calling listFinancialEventGroups operation for different date ranges.

When calling listFinancialEventGroups with a larger date range, it is returning a different OriginalTotal than when calling it with a smaller date range.

Expected behavior:
Calling the operation with different date ranges should have the same data for the groups within both date ranges.

Actual Behavior:
The Original Total is different when using different date ranges.

The only difference that I can see is that when using a large date range, we need to use the nextToken to get more groups, it seems to be that when you use a nextToken to get groups, the originalTotal is wrong.

**Comment by jawheral** [comment]
Hi @shlomieconnect,

Without exact FinancialEventGroupId values, date ranges, sellerId, requests and responses, we won't be able to troubleshoot or fix the issue. For this, please create a case with [Developer Support](https://sellercentral.amazon.com/sp-api-status) and provide all necessary details. You might share the case id here once created so I can track it.

Best,
Jawher
Selling Partner Developer Services

**Comment by shlomieconnect** [comment]
@jawheral I have already opened a case a week ago. I was just curious to see if other people were experiencing the same issue or it's just me.

**Comment by jawheral** [comment]
Hi @shlomieconnect,

This issue should be fixed by now. Can you confirm that it is fixed?

Best,
Jawher
Selling Partner Developer Services

**Comment by shlomieconnect** [comment]
I just checked, the issue is still not fixed. 

Request ID: 5e745d7d-a32c-4473-bdc4-25a9f307e83e
Time Stamp: Tue, 28 Jan 2025 21:16:06 GMT

**Comment by jawheral** [comment]
Hi @shlomieconnect,

Is this issue fixed for you now?

Best,
Jawher
Selling Partner Developer Services

**Comment by shlomieconnect** [comment]
No. 

6558ce2e-f61e-4fb7-a8d2-1375757e5613
Fri, 07 Feb 2025 14:48:53 GMT
