### ISSUE TITLE
FBA Inbound - get labels returning "InvalidInput | We are not able to fetch carrier labels while it is required..." on APC LTL shipments since 6/6/25

### ISSUE THREAD

**Issue by MetaMan2023** [amzn/selling-partner-api-models#4811]
As of yesterday we are receiving random errors when using "get labels" to pull labels for APC LTL shipments.

This has worked fine for months with no issues, and APC UPS work fine.

We are now getting this error:

InvalidInput | We are not able to fetch carrier labels while it is required. Please check the parameter request. It is possible you use incorrect number of total packages and page index.

The error message is also very odd/confusing and strangely worded.

I have opened a case as well -- is anyone else experiencing this issue?

@puppsupr

**Comment by Yayayay218** [comment]
Same here — I’m facing that issue as well.

**Comment by Averag1Enjoyer** [comment]
Same on our side. Until June 5th, 2025, our logic had also been working correctly for months, and we hadn't changed anything in it. However, now, unexpectedly, we started receiving this strange error when trying to retrieve shipment labels using the getLabels operation. We have already submitted a support request to Amazon support.

**Comment by Yayayay218** [comment]
Hi @MetaMan2023, @Averag1Enjoyer 
I've just figured out a fix for this issue: try setting PageType to 'PackageLabel_Thermal_NonPCP' if you're working with non-Amazon-partnered shipments. I tested it and it worked.

**Comment by Averag1Enjoyer** [comment]
Hi @Yayayay218. Thank you! It worked.

**Comment by MetaMan2023** [comment]
I can confirm this fix works for NON PARTNERED UPS as well -- we have not yet tested on PARTNERED LTL yet which is the one we had on Friday.  We will test later in afternoon.

I have escalated to an internal FBA API contact and they are aware and looking into this.

**Comment by haoxi911** [comment]
I encountered the same issue today. It seems both LTL and non-partnered SPD have to set PageType to `PackageLabel_Thermal_NonPCP`. I can still use `PackageLabel_Thermal` for partnered SPD.

**Comment by B3lg4r4th** [comment]
We can confirm this issue on our end as well

**Comment by puppsupr** [comment]
Hi Team,
This issue has been identified and team is working on the fix. Will post updates as I hear back.

**Comment by AshwinPitroda** [comment]
Hi @puppsupr I am also facing same issues while generating carton labels recently. Please let us know when it's fixed. Thanks

**Comment by hamduc7** [comment]
Hi @puppsupr 
We also have this issue. Please fix it as soon as possible.

Thank you

**Comment by razvanaldo** [comment]
We are also affected by this issue, we are interested in an update, please let us know,
Thank you,
Razvan

**Comment by MetaMan2023** [comment]
OK I have multiple updates:

>> From a contact in the API team earlier today:

They inform me the "issue has been fixed" and the rumor is they will be posting updates here -- but I have not personally tested to see if this is the case.

>> From a support case I opened (30 mins ago) I received a separate answer:

"I hope this email finds you well. I am writing regarding your recent label request for shipment FBA18XZWBFS0.

We noticed that you requested a label with pageType "PackageLabel_Thermal", which is not supported by the shipping service icso-freight-us that is assigned to your shipment.

For shipment FBA18XZWBFS0, please use one of the following supported label types:

PackageLabel_Thermal_NonPCP
PackageLabel_Letter_6
PackageLabel_Plain_Paper


We also send out a fix to add a alias PackageLabel_Thermal to mitigate the issue. After deploying it, you are going be able to use PackageLabel_Thermal to print label, give us some time to process this update for now we recommend you to use the ones mentioned above.

If you need any assistance or have questions, please don't hesitate to reach out."

====

That support case answer sounds like they are aware of it as they say "send out a fix".    The support answer is confusing though it sounds like going forward we need to use specific "PackageLabel_????" requests depending on the shipment type, however they are working on a fix to the "PackageLabel_Thermal" option.

Can anyone test if the issue has been resolved with PackageLabel_Thermal yet?

**Comment by hamduc7** [comment]
Dear All,
I still see this error on my shipment. Using PackageLabel_Letter_2 will not work
But using PackageLabel_Thermal works

I wonder if Amazon has fixed the PackageLabel_Letter_X or not

**Comment by puppsupr** [comment]
Hi,
This issue has been resolved. Please [open a support](https://developer.amazonservices.com/support) case if you face any other troubleshooting issue.

**Comment by hamduc7** [comment]
Dear @puppsupr 

I still see the error on my end when using 'PackageLabel_Letter_2'. It works if I use 'PackageLabel_Thermal'

`We are not able to fetch carrier labels while it is required. Please check the parameter request or call GetValidPageTypesForShipment to check valid PageType for the shipment. It is also possible you use incorrect number of total packages and page index.`

It appears that the error message has been updated. It mentions GetValidPageTypesForShipment, but I cannot find this API
